### ISSUE TITLE
Notarization

### ISSUE THREAD

**Issue by cannonsmith** [miyako/4d-plugin-file-information#1]
This plugin won't load in the development environment on Catalina (in 4D v17.3HF1) because, I think, it isn't notarized. Could it be updated so it will load correctly? Thank you.

**Comment by miyako** [comment]
I've updated release [2.0](https://github.com/miyako/4d-plugin-file-information/releases/tag/2.0)

although, this plugin is for windows, you don't need it on Mac.

**Comment by cannonsmith** [comment]
> I've updated release 2.0

Thank you very much! I can now load the structure properly in Catalina.


> although, this plugin is for windows, you don't need it on Mac.

Of course, but it still sits in the Plugins folder on my Mac and 4D wasn’t happy with it. :-)

Thanks again.

--
Cannon.Smith
Synergy Farm Solutions Inc.
Aetna, AB Canada
<cannon@synergyfarmsolutions.com>
<www.synergyfarmsolutions.com>
